---

prometheus_enabled: true
hyperauth_enabled: true

# prometheus_install_namespace  
#prometheus_namespace: "monitoring"


# 1. prometheus_operator parameters
prometheus_operator_image_repo: "{{ quay_image_repo }}/coreos/prometheus-operator"
prometheus_operator_image_tag: "v0.34.0"
config_reloader_image_repo: "{{ quay_image_repo }}/coreos/configmap-reload"
config_reloader_image_tag: "v0.0.1"
configmap_reloader_image_repo: "{{ quay_image_repo }}/coreos/prometheus-config-reloader"
configmap_reloader_image_tag: "v0.34.0"

# 2. alertmanager parameters
alertmanager_image_repo: "{{ quay_image_repo }}/prometheus/alertmanager"
alertmanager_image_tag: "v0.20.0"


# 3. node exporter parameters
node_exporter_image_repo: "{{ quay_image_repo }}/prometheus/node-exporter"
node_exporter_image_tag: "v0.18.1"
kube_rbac_proxy_image_repo2: "{{ quay_image_repo }}/coreos/kube-rbac-proxy"
kube_rbac_proxy_image_tag2: "v0.4.1"

# 4. proemtheus adapter parameters
prometheus_adapter_image_repo: "{{ quay_image_repo }}/coreos/k8s-prometheus-adapter-amd64"
prometheus_adapter_image_tag: "v0.5.0"


# 5. prometheus parameters
prometheus_image_repo: "{{ quay_image_repo }}/prometheus/prometheus"
prometheus_image_tag: "v2.11.0"
prometheus_pvc: "10Gi"

# 6. kube state metrics parameters
kube_state_metrics_image_repo: "{{ quay_image_repo }}/coreos/kube-state-metrics"
kube_state_metrics_image_tag: "v1.8.0"
master_ip: {}
