---
- block:
  - name: copy required files | Ensure directory exist
    file:
      path: "{{ files_repo | regex_replace('^file://', '') }}"
      state: directory

  - name: copy required files | Copy files
    copy:
      src: "{{ files_repo | regex_replace('^file://', '') }}/"
      dest: "{{ files_repo | regex_replace('^file://', '') }}/"
